name: Run automated system tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - support/**
    types: [opened, synchronize]
    paths-ignore:
      - '**/*.md'
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      neofs_s3_gw_ref:
        description: 'neofs-s3-gw ref. Default ref - latest master. Examples: v0.27.0, 8fdcc6d7e798e6511be8806b81894622e72d7fdc, branch_name'
        required: false
        default: ''

permissions: write-all

jobs:
  run_system_tests:
    uses: nspcc-dev/neofs-testcases/.github/workflows/system-tests.yml@master
    with:
      neofs_network_domain: ${{ vars.TEST_RESULTS_NEOFS_NETWORK_DOMAIN }}
      neofs_http_gate: ${{ vars.TEST_RESULTS_HTTP_GATE }}
      neofs_store_objects_cid: ${{ vars.TEST_RESULTS_CID }}
      neofs_pr_expiration_period: ${{ vars.PR_EXPIRATION_PERIOD }}
      neofs_master_expiration_period: ${{ vars.MASTER_EXPIRATION_PERIOD }}
      neofs_manual_expiration_period: ${{ vars.MANUAL_RUN_EXPIRATION_PERIOD }}
      neofs_other_expiration_period: ${{ vars.OTHER_EXPIRATION_PERIOD }}
      neofs_testcases_commit: 'master'
      neofs_s3_gw_commit: ${{ github.event.inputs.neofs_s3_gw_ref }}
      tests_path: 'pytest_tests/tests/s3'
      tests_parallel_level: 3
      os: '[{runner: "ubuntu-latest", binary: "linux-amd64"}, {runner: "macos-14", binary: "darwin-arm64"}]'
    secrets: inherit
